CREATE DATABASE IF NOT EXISTS clinic_db;

USE clinic_db;

CREATE TABLE IF NOT EXISTS CITY (
    CityId INT AUTO_INCREMENT PRIMARY KEY,
    City_Name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PATIENT (
    PatientId INT AUTO_INCREMENT PRIMARY KEY,
    Full_Name VARCHAR(150) NOT NULL,
    Gender VARCHAR(20) NOT NULL,
    Birth_Date DATE NOT NULL,
    CityId INT NOT NULL,
    CONSTRAINT fk_patient_city
    FOREIGN KEY (CityId) REFERENCES CITY (CityId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS DIAGNOSIS (
    DiagnosisId INT AUTO_INCREMENT PRIMARY KEY,
    Diagnosis_Name VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS VISIT (
    VisitId INT AUTO_INCREMENT PRIMARY KEY,
    PatientId INT NOT NULL,
    DiagnosisId INT NOT NULL,
    Visit_Date DATE NOT NULL,
    Clinical_Notes TEXT,
    CONSTRAINT fk_visit_patient
    FOREIGN KEY (PatientId) REFERENCES PATIENT (PatientId)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT fk_visit_diagnosis
    FOREIGN KEY (DiagnosisId) REFERENCES DIAGNOSIS (DiagnosisId)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

INSERT INTO CITY (City_Name) VALUES ('Sumy'), ('Kyiv'), ('Lviv') ON DUPLICATE KEY UPDATE City_Name = VALUES(City_Name);

INSERT INTO DIAGNOSIS (Diagnosis_Name) VALUES ('Flu'), ('Covid-19'), ('Allergic') ON DUPLICATE KEY UPDATE Diagnosis_Name = VALUES(Diagnosis_Name);
